ir_left:
  width: 848
  height: 480
  fx: 0.0
  fy: 0.0
  cx: 0.0
  cy: 0.0
  distortion_model: brown_conrady
  distortion_coeffs: [0.0, 0.0, 0.0, 0.0, 0.0]
ir_right:
  width: 848
  height: 480
  fx: 0.0
  fy: 0.0
  cx: 0.0
  cy: 0.0
  distortion_model: brown_conrady
  distortion_coeffs: [0.0, 0.0, 0.0, 0.0, 0.0]
color:
  width: 640
  height: 480
  fx: 0.0
  fy: 0.0
  cx: 0.0
  cy: 0.0
  distortion_model: inverse_brown_conrady
  distortion_coeffs: [0.0, 0.0, 0.0, 0.0, 0.0]
extrinsics:
  ir_left_to_ir_right:
    rotation: [1, 0, 0, 0, 1, 0, 0, 0, 1]
    translation: [-0.05, 0.0, 0.0]
  ir_left_to_color:
    rotation: [1, 0, 0, 0, 1, 0, 0, 0, 1]
    translation: [0.015, 0.0, 0.0]
